server:
  port: 8080  # 应用程序端口号

spring:
  devtools:
    restart:
      enabled: true  # 启用 Spring DevTools 自动重启功能
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动类名
    url: jdbc:mysql://106.75.210.243:3306/hk-admin?serverTimezone=Asia/Shanghai&useSSL=false  # 数据库连接URL
    username: hk-admin  # 数据库用户名
    password: eT2nDtDhYbjTyMeH  # 数据库密码
    type: com.zaxxer.hikari.HikariDataSource  # 数据源类型
    hikari:
      maximum-pool-size: 10  # 数据源最大连接池大小
      minimum-idle: 5  # 数据源最小空闲连接数
      idle-timeout: 180000  # 连接在池中闲置的最长时间（毫秒）
      pool-name: SpringBootJPAHikariCP  # 连接池名称
      auto-commit: true  # 自动提交事务
      connection-timeout: 30000  # 获取连接的超时时间（毫秒）
      connection-test-query: SELECT 1  # 测试连接的SQL查询
      max-lifetime: 1800000  # 连接的最长生命周期（毫秒）
      connection-init-sql: SELECT 1  # 初始化连接时执行的SQL语句
      validation-timeout: 5000  # 连接验证超时时间（毫秒）
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1  # 逻辑删除标记值（1表示已删除）
      logic-not-delete-value: 0  # 逻辑删除标记值（0表示未删除）
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名规则映射
    jdbc-type-for-null: 'null'  # 空值的JDBC类型
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis日志输出实现类

############## Sa-Token 配置 (官网: https://sa-token.cc) ##############
sa-token:
  # Token 存储的 Cookie 名称
  token-name: saToken
  # Token 的超时时间（秒）-1 表示永不过期
  timeout: 2592000
  # Token 的最长活动时间（秒）-1 表示不限制
  active-timeout: -1
  # 是否允许并发登录，true 表示允许，false 表示不允许
  is-concurrent: true
  # 是否共享 Token，true 表示共享，false 表示不共享
  is-share: true
  # Token 生成方式（uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否记录 Sa-Token 的日志
  is-log: true
